COPY CONCEPT FROM '/home/junior/Downloads/synpuf5pct_20180710/concept.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_ANCESTOR FROM '/home/junior/Downloads/synpuf5pct_20180710/concept_ancestor.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_CLASS FROM '/home/junior/Downloads/synpuf5pct_20180710/concept_class.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
--COPY CONCEPT_HIERARCHY FROM '/home/junior/Downloads/synpuf5pct_20180710/concept_hierarchy.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_RELATIONSHIP FROM '/home/junior/Downloads/synpuf5pct_20180710/concept_relationship.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_SYNONYM FROM '/home/junior/Downloads/synpuf5pct_20180710/concept_synonym.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONDITION_ERA FROM '/home/junior/Downloads/synpuf5pct_20180710/condition_era.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
\ COPY CONDITION_OCCURRENCE FROM '/home/junior/Downloads/synpuf5pct_20180710/condition_occurrence.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY COST FROM '/home/junior/Downloads/synpuf5pct_20180710/cost.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
--COPY DEATH FROM '/home/junior/Downloads/synpuf5pct_20180710/death.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DEVICE_EXPOSURE FROM '/home/junior/Downloads/synpuf5pct_20180710/device_exposure.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DOMAIN FROM '/home/junior/Downloads/synpuf5pct_20180710/domain.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DRUG_ERA FROM '/home/junior/Downloads/synpuf5pct_20180710/drug_era.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DRUG_EXPOSURE FROM '/home/junior/Downloads/synpuf5pct_20180710/drug_exposure.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DRUG_STRENGTH FROM '/home/junior/Downloads/synpuf5pct_20180710/drug_strength.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY LOCATION FROM '/home/junior/Downloads/synpuf5pct_20180710/location.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY MEASUREMENT FROM '/home/junior/Downloads/synpuf5pct_20180710/measurement.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY OBSERVATION FROM '/home/junior/Downloads/synpuf5pct_20180710/observation.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY OBSERVATION_PERIOD FROM '/home/junior/Downloads/synpuf5pct_20180710/observation_period.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PAYER_PLAN_PERIOD FROM '/home/junior/Downloads/synpuf5pct_20180710/payer_plan_period.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PERSON FROM '/home/junior/Downloads/synpuf5pct_20180710/person.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PROCEDURE_OCCURRENCE FROM '/home/junior/Downloads/synpuf5pct_20180710/procedure_occurrence.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PROVIDER FROM '/home/junior/Downloads/synpuf5pct_20180710/provider.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY RELATIONSHIP FROM '/home/junior/Downloads/synpuf5pct_20180710/relationship.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY VISIT_OCCURRENCE FROM '/home/junior/Downloads/synpuf5pct_20180710/visit_occurrence.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY VOCABULARY FROM '/home/junior/Downloads/synpuf5pct_20180710/vocabulary.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CARE_SITE FROM '/home/junior/Downloads/synpuf5pct_20180710/care_site.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CDM_SOURCE FROM '/home/junior/Downloads/synpuf5pct_20180710/CDM_SOURCE.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';






COPY omop5.ATTRIBUTE_DEFINITION TO '/tmp/ATTRIBUTE_DEFINITION.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CARE_SITE TO '/tmp/CARE_SITE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CDM_SOURCE TO '/tmp/CDM_SOURCE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.COHORT TO '/tmp/COHORT.csv' DELIMITER ',' CSV HEADER;

COPY omop5.COHORT_ATTRIBUTE TO '/tmp/COHORT_ATTRIBUTE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.COHORT_DEFINITION TO '/tmp/COHORT_DEFINITION.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONCEPT TO '/tmp/CONCEPT.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONCEPT_ANCESTOR TO '/tmp/CONCEPT_ANCESTOR.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONCEPT_CLASS TO '/tmp/CONCEPT_CLASS.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONCEPT_RELATIONSHIP TO '/tmp/CONCEPT_RELATIONSHIP.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONCEPT_SYNONYM TO '/tmp/CONCEPT_SYNONYM.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONDITION_ERA TO '/tmp/CONDITION_ERA.csv' DELIMITER ',' CSV HEADER;

COPY omop5.CONDITION_OCCURRENCE TO '/tmp/CONDITION_OCCURRENCE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.COST TO '/tmp/COST.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DEATH TO '/tmp/DEATH.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DEVICE_EXPOSURE TO '/tmp/DEVICE_EXPOSURE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DOMAIN TO '/tmp/DOMAIN.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DOSE_ERA TO '/tmp/DOSE_ERA.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DOSE_UNIT TO '/tmp/DOSE_UNIT.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DRUG_ERA TO '/tmp/DRUG_ERA.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DRUG_EXPOSURE TO '/tmp/DRUG_EXPOSURE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.DRUG_STRENGTH TO '/tmp/DRUG_STRENGTH.csv' DELIMITER ',' CSV HEADER;

COPY omop5.FACT_RELATIONSHIP TO '/tmp/FACT_RELATIONSHIP.csv' DELIMITER ',' CSV HEADER;

COPY omop5.LOCATION TO '/tmp/LOCATION.csv' DELIMITER ',' CSV HEADER;

COPY omop5.MEASUREMENT TO '/tmp/MEASUREMENT.csv' DELIMITER ',' CSV HEADER;

COPY omop5.METADATA TO '/tmp/METADATA.csv' DELIMITER ',' CSV HEADER;

COPY omop5.NOTE TO '/tmp/NOTE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.NOTE_NLP TO '/tmp/NOTE_NLP.csv' DELIMITER ',' CSV HEADER;

COPY omop5.OBSERVATION TO '/tmp/OBSERVATION.csv' DELIMITER ',' CSV HEADER;

COPY omop5.OBSERVATION_PERIOD TO '/tmp/OBSERVATION_PERIOD.csv' DELIMITER ',' CSV HEADER;

COPY omop5.PAYER_PLAN_PERIOD TO '/tmp/PAYER_PLAN_PERIOD.csv' DELIMITER ',' CSV HEADER;

COPY omop5.PERSON TO '/tmp/PERSON.csv' DELIMITER ',' CSV HEADER;

COPY omop5.PROCEDURE_OCCURRENCE TO '/tmp/PROCEDURE_OCCURRENCE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.PROVIDER TO '/tmp/PROVIDER.csv' DELIMITER ',' CSV HEADER;

COPY omop5.RELATIONSHIP TO '/tmp/RELATIONSHIP.csv' DELIMITER ',' CSV HEADER;

COPY omop5.SOURCE_TO_CONCEPT_MAP TO '/tmp/SOURCE_TO_CONCEPT_MAP.csv' DELIMITER ',' CSV HEADER;

COPY omop5.SPECIMEN TO '/tmp/SPECIMEN.csv' DELIMITER ',' CSV HEADER;

COPY omop5.VISIT_DETAIL TO '/tmp/VISIT_DETAIL.csv' DELIMITER ',' CSV HEADER;

COPY omop5.VISIT_OCCURRENCE TO '/tmp/VISIT_OCCURRENCE.csv' DELIMITER ',' CSV HEADER;

COPY omop5.VOCABULARY TO '/tmp/VOCABULARY.csv' DELIMITER ',' CSV HEADER;









